resolver: lts-6.13
packages:
- '.'
- location:
      git: https://github.com/agrafix/Spock.git
      commit: 77333a2de5dea0dc8eba9432ab16864e93e5d70e
  subdirs:
    - Spock-core
    - reroute
extra-deps:
  - digestive-functors-0.8.1.0
