flags: {}
packages:
- '.'
- location:
      git: git@github.com:agrafix/Spock
      commit: 8a83cfa4646acfe0a7e0ae5bf2be342d926df5c5
  subdirs:
    - Spock-core
    - reroute
extra-deps:
resolver: lts-5.8
